## Случайное число — это число, которое возникает в результате случайного процесса.

Псевдослучайные числа — это такая последовательность чисел, которая возникает с помощью применения математических формул к какому-то исходному числу (например, текущему времени в микросекундах). Элементы, получаемые таким образом, почти не зависят друг от друга: например, при генерации следующего 0 или 1 не имеет значения, что выпало ранее — 0 или 1.

## Случайные числа в NumPy

Для генерации псевдослучайных чисел в NumPy существует подмодуль **random**.

Самой «базовой» функцией в нём можно считать функцию **rand**. По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):

In [1]:
import numpy as np
np.random.rand()

0.9519217650276951

Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:

In [2]:
np.random.rand() * 100

81.94719480363598

На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов через запятую целые числа, которые задают форму генерируемого массива. Например, получим массив из пяти случайных чисел:

In [3]:
np.random.rand(5)

array([0.5012532 , 0.05825363, 0.03756979, 0.5048977 , 0.01215482])

Массив из двух случайных строк и трёх столбцов:

In [4]:
np.random.rand(2, 3)

array([[0.02043189, 0.43409252, 0.28119631],
       [0.62537092, 0.42274835, 0.99012452]])

Функция rand может принимать неограниченное число целых чисел для задания формы массива:

In [ ]:
np.random.rand(2, 3, 4, 10, 12, 23)

***Обратите внимание, что обычно форму массивов мы задавали в функциях NumPy одним числом или кортежем, а не перечисляли её в виде аргументов через запятую***.

Если передать в rand кортеж, возникнет ошибка:

In [ ]:
shape = (3, 4)
np.random.rand(shape)

Конечно, можно было бы распаковать кортеж, чтобы избавиться от ошибки:

In [7]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.80131755, 0.51378372, 0.27659397, 0.32081615],
       [0.32691177, 0.39703197, 0.87634249, 0.83345554],
       [0.59401304, 0.52026757, 0.52254981, 0.37203414]])

Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки. Она называется **sample**

In [8]:
shape = (2, 3)
np.random.sample(shape)

array([[0.31023688, 0.31401543, 0.45471061],
       [0.20035221, 0.57870595, 0.37823108]])

Возможно, именно функция **sample** покажется вам удобнее, поскольку информацию о форме массива обычно удобнее хранить в коде в виде кортежа и не задумываться потом о его распаковке. В остальном функция **sample** не отличается от **rand**.

Не всегда требуются числа в диапазоне именно от 0 до 1. На самом деле с помощью специальных формул можно из диапазона от 0 до 1 получить любой другой желаемый диапазон, однако это не требуется делать самостоятельно — в NumPy доступна функция **uniform**:

uniform(low=0.0, high=1.0, size=None)

Первые два аргумента — нижняя и верхняя границы диапазона в формате float, третий опциональный аргумент — форма массива (если не задан, возвращается одно число). Форма массива задаётся кортежем или одним числом.

In [13]:
print(np.random.uniform()) #Запуск без аргументов эквивалентен работе функций rand или sample:
print(np.random.uniform(-30, 50)) #Зададим границы диапазона от -30 до 50:
print(np.random.uniform(0.5, 0.75, size=5)) #Получим пять чисел в интервале от 0.5 до 0.75:
print(np.random.uniform(-1000, 500, size=(2, 3))) #Получим массив из двух строк и трёх столбцов из чисел в интервале от -1000 до 500:

0.1216214851677403
-15.821009345440737
[0.58185395 0.60585728 0.53336698 0.50305798 0.50694933]
[[ 343.94470203 -402.25158392  151.95617158]
 [ 306.58913333  356.43179208  -57.40975481]]
