In [1]:
import numpy as np

## Генерация выборок
Случайные числа можно использовать и для работы с уже существующими данными. Иногда для проверки гипотез о данных бывает удобно перемешать значения, чтобы проверить, является ли наблюдаемая закономерность случайной.

Просто перемешать все числа в массиве позволяет функция **random.shuffle**

In [ ]:
#Возьмём массив из целых чисел от 0 до 5 и перемешаем его:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr)) #Функция random.shuffle перемешивает тот массив, к которому применяется, и возвращает None.
arr

[0 1 2 3 4 5]
None


array([5, 2, 3, 0, 1, 4])

Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию *random.permutation*. 
Она принимает на вход один аргумент — или массив целиком, или одно число:

In [3]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
print(playlist)

['Pink Floyd' 'Deep Purple' 'The Beatles' 'ACDC']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


Обратите внимание, что необязательно передавать в функцию сразу массив: в этот раз мы передали в качестве аргумента список и ошибки не возникло. При этом на выходе получился уже NumPy-массив (это заметно по отсутствию запятых при печати массива). Сам список playlist при этом остался без изменений.

In [4]:
# Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), 
# где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.
np.random.permutation(10)

array([7, 5, 1, 9, 6, 8, 0, 3, 4, 2], dtype=int32)

Чтобы получить случайный набор объектов из массива, используется функция **random.choice**:

choice(a, size=None, replace=True)

- **a** — одномерный массив или число для генерации arange(a);
- **size** — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
- **replace** — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

Выберем случайным образом из списка двоих человек, которые должны будут выступить с отчётом на этой неделе. Для этого из списка имён (опять же, можно передавать в функцию choice не NumPy-массив, а список) получим два случайных объекта без повторений (логично, что нужно выбрать двух разных людей). Сделать это можно вот так:

In [9]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Kate' 'Maria']


In [ ]:
#Если попытаться получить без повторений массив большего размера, чем имеется объектов в исходном, возникнет ошибка:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)
# ValueError: Cannot take a larger sample than population when 'replace=False'
# Ошибка значения: нельзя получить выборку больше, чем популяция (популяция — весь доступный набор объектов, из которого 
# получаем выборку), если replace=False (то есть выборка без повторений).

Выборка с повторениями используется по умолчанию. Она применяется в том случае, когда мы допускаем, что объекты могут повторяться.

Например, получим случайную последовательность, которая образуется в результате десяти подбрасываний игральной кости:

In [ ]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[4 4 3 3 3 2 3 4 1 4]
