In [2]:
import numpy as np

In [2]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [ ]:
#для задания
A0 = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
# обратная матрица - все ок
A0_inv=np.linalg.inv(A0)
print('A1 inversed:\n',A0_inv)

A1 inversed:
 [[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]


In [3]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [ ]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


In [ ]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

In [ ]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

In [ ]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

In [ ]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

In [ ]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

In [ ]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

In [ ]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

In [ ]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

In [ ]:
print('det(A1)):\n',np.linalg.det(A1))

In [ ]:
print('det(A2)):\n',np.linalg.det(A2))

In [ ]:
print('det(A3)):\n',np.linalg.det(A3))

In [ ]:
# обратная матрица - неустойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

In [ ]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

In [ ]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

In [ ]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

In [ ]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

In [ ]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))

##### Задание 10.1
Найдите матрицу, обратную матрице A.
В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.

In [3]:
A0 = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
# обратная матрица - все ок
A0_inv=np.linalg.inv(A0)
print('A1 inversed:\n',A0_inv[1,0])

A1 inversed:
 0.3750000000000005


In [4]:
#для заданий далее
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

#### Задание 10.2
Найдите ранг системы векторов v1, v2, v3, v4. 
Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [5]:

A = np.array([v1,v2,v3,v4]).T
np.linalg.matrix_rank(A)

np.int64(4)

Ранг матрицы A, составленной из векторов v1, v2, v3, v4 равен 4, что равно количеству векторов в системе. 
Это значит, что система векторов является линейно независимой.

##### Задание 10.4
Найдите матрицу Грама системы векторов v1, v2, v3, v4: . В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [6]:
G = A.T @ A
print(G[0,3])

-35


##### Задание 10.5
Найдите определитель матрицы Грама  системы v1, v2, v3, v4. Ответ округлите до целого числа.

In [ ]:
det = np.linalg.det(G)
print(round(det))

3716648


Определитель матрицы Грамма отличен от нуля, значит матрица не вырождена.

##### Задание 10.7

Найдите обратную матрицу к матрице Грама  системы v1, v2, v3, v4. В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [9]:
G_inv = np.linalg.inv(G)
print(round(G_inv[2,0], 3))

-0.026
