С векторами в NumPy можно производить арифметические операции: складывать, вычитать, умножать друг на друга, возводить один вектор в степень другого и т. д.

Операция, применённая к двум векторам, на самом деле применяется поэлементно. То есть при сложении двух векторов первым элементом нового вектора будет сумма первых элементов исходных векторов, вторым — сумма вторых элементов и т. д.

Произведём сложение двух векторов:

In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
print(vec1 + vec2)

[14.  10.  10.6 15.5]


Что бы произошло при сложении двух списков? Их элементы просто объединились бы в один список:

In [2]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
print(list1 + list2)

[2, 4, 7, 2.5, 12, 6, 3.6, 13]


Чтобы сложить два этих списка поэлементно, нам пришлось бы написать списочное сокращение с применением функции zip():

In [3]:
res = [x + y for x, y in zip(list1, list2)]
print(res)

[14, 10, 10.6, 15.5]


Для совершения арифметических операций с векторами они должны быть одинаковой длины.

Поэлементно умножим два вектора одинаковой длины:

In [4]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
print(vec1 * vec2)

[24.  24.  25.2 32.5]


Исключением является случай, когда операция происходит с вектором и одним числом. Например, вектор целиком можно умножить на число или возвести в степень этого числа:

In [ ]:
vec = np.arange(5)
print(vec * 10)
print(vec ** 2)

[ 0 10 20 30 40]
[ 0  1  4  9 16]


Также векторы можно сравнивать друг с другом поэлементно:

In [7]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
print(vec1 > vec2)

[False False  True False]


В результате получаем вектор исходной длины из булевых переменных, которые соответствуют результату поэлементного сравнения чисел из двух векторов.

Аналогично можно сравнивать вектор с числом:

In [8]:
vec = np.array([14,15,9,26,53,5,89])
print(vec <= 26)

[ True  True  True  True False  True False]
